---
name: Build

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  build:
    name: Build

    runs-on: ubuntu-22.04

    steps:
      - name: BuildX
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: Build
        uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # v6.4.1
        with:
          no-cache: true
          platforms: linux/amd64,linux/arm64
