---
name: Build

"on": push

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: BuildX
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4.0.0
        with:
          no-cache: true
          platforms: linux/amd64,linux/arm64
